### ISSUE TITLE
Broken master

### ISSUE THREAD

**Issue by sschneiders** [EmbeddedMontiArc/EmbeddedMontiArc#4]
Your latest two comments broke the master builds in travis.
Please fix this.

**Comment by vonwenckstern** [comment]
your last commit is available in your progaddict branch,
I reverted the master branch and redraw you the permission to commit to it.
Please commit to your branch and Evgeny can integrate your code if it builds does not contain Kotlin

**Comment by progaddict** [comment]
I've found the problem. it is actually with the coveralls-maven-plugin:

`Failed to execute goal [32morg.eluder.coveralls:coveralls-maven-plugin:4.3.0:report[m [1m(default-cli)[m on project [36membedded-montiarc[m: [1;31mI/O operation failed[m: No source found for de/monticore/lang/embeddedmontiarc/ComponentParametersSubstitutions.kt -> [1m[Help 1][m
`
it looks like the plugin does not like bytecode produced by kotlin:
https://youtrack.jetbrains.com/issue/KT-9766

Sorry, guys, for breaking the build. I've checked it locally, the project actually builds but the coverage tool does not like the report being generated.

For this project I'm going to convert kotlin to java since there are not that many classes. But for other kotlin projects I'll need to find an appropriate coverage tool/plugin.
